title : 五条人信息网
name: '五条人信息网'
description: '五条人信息网'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

collections:
  posts:
    title: Essays
    default_open: true
    output: true
  interviews:
    title: 访谈
    default_open: true
    output: true
  songs:
    title: 歌曲
    default_open: true
    output: true
  videos:
    title: 视频
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: Interviews
    values:
      title: 访谈
      permalink: /interviews/:title
  - scope:
      type: Songs
    values:
      title: 歌曲
      permalink: /songs/:title
  - scope:
      type: Videos
    values:
      title: 视频
      permalink: /videos/:title

plugins:
  - jekyll-sitemap

cdn: "https://cdn.jsdelivr.net/gh/wutiaoreninfo/wutiaoreninfo.github.io@main"
#cdn: ""